### PR TITLE
Changed Led interrupt handling to ICACHE_RAM_ATTR. (#29)

### LINKED ISSUE #29: Arduino Core fix
@pattyland  wrote in https://github.com/ThomDietrich/SenseoWifi/pull/28:

> Hi,
> 
> there seems to be [problems with newer version of arduino core](https://github.com/esp8266/Arduino/issues/6127). 
> My D1 Mini would crash at boot with a `ISR not in IRAM` error. 
> 
> This PR ist the [quick fix](https://github.com/esp8266/Arduino/issues/6127), [this is the longer (and better?) fix](https://github.com/esp8266/Arduino/issues/6127#issuecomment-497785103) I guess.
> 
> Best regards
> Sören

### PR DESCRIPTION
**Pull request by bschlaack**
Changed Led interrupt handling to ICACHE_RAM_ATTR. Works with actual espressi8266 2.7.1. 
Changed platformio.ini to get actual version of espressi8266 

Fixes #29

### CODE REVIEW

File: src/SenseoWifi.cpp [hunk 1]
```diff
@@ -14,6 +14,8 @@ Released under some license.
 #include "constants.h"
 #include "testIO.cpp"
 
+void ICACHE_RAM_ATTR ledChangedHandler();
```
Comment (ThomDietrich) [inline src/SenseoWifi.cpp:17]: Is this line needed?

File: src/SenseoWifi.cpp [hunk 2]
```diff
@@ -251,14 +253,29 @@ void senseoStateEntryAction() {
   }
 }
 
+void onHomieEvent(const HomieEvent &event)
+{
+  // The device rebooted when attachInterrupt was called in setup()
+  // before Wifi was connected and interrupts were already coming in.
```
Comment (ThomDietrich) [inline src/SenseoWifi.cpp:259]: Is that so? Maybe new behavior with the latest code base I didn't catch. Thanks for the additional fix ;)
In case you add another commit to this PR: Could you please format this part in alignment with the code style of the file? Thanks!

**Comment by ThomDietrich** [comment]
Thanks for the addition and testing!

Just for my info: Do you have a fully working machine set up?

File: src/SenseoWifi.cpp (hunk 2 above)
Comment (bschlaack) [reply src/SenseoWifi.cpp:259]: The interrupts begin to fire before wifi is up. When the led-change event is triggered but the wifi connection is not established it may results in an error accessing the broker.

File: src/SenseoWifi.cpp (hunk 1 above)
Comment (bschlaack) [reply src/SenseoWifi.cpp]: No, you are right ... is removed in a following commit. (together with codestyle changes ;) )

**Comment by bschlaack** [comment]
Yes ... I "improved" an old 7817. But I have still some problems ... The first power on command is ignored. When I send power off the senseo starts ... O.O ... then I send power on ... nothing changes ... good ... the next power off works right ... senso shuts off ... from this point the power commands are interpreted right ...

**Comment by ThomDietrich** [comment]
Thanks for your contribution

While you are still in development mode: Would you fancy to implement a tone when the machine is connected to Wifi? https://github.com/ThomDietrich/SenseoWifi/issues/27

> But I have still some problems ... 

My feeling is that every machine has slightly different timings. Did you check if yours are within the limits given in the config? You can use testIO.cpp for that

**Comment by bschlaack** [comment]
> While you are still in development mode: Would you fancy to implement a tone when the machine is connected to Wifi? #27

I'll give it a try ... I play with a little melody ... it works it where the other status sound are placed, but in the eventhanding it sounds like a scratch ... I work on it ... ;)

> My feeling is that every machine has slightly different timings. Did you check if yours are within the limits given in the config? You can use testIO.cpp for that

Not tested yet ... but I will! Thanks for advice!
